<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="97101901-02.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW AdditionalNote CDATA #IMPLIED>
  <!ATTLIST ROW Approved_by CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW change_index CDATA #IMPLIED>
  <!ATTLIST ROW Cust__No CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Edited_by CDATA #IMPLIED>
  <!ATTLIST ROW Last_Rev__Date CDATA #IMPLIED>
  <!ATTLIST ROW Product_No_ CDATA #IMPLIED>
  <!ATTLIST ROW Product_Number CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Release_No CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW descriptions CDATA #IMPLIED>
  <!ATTLIST ROW mfg CDATA #IMPLIED>
  <!ATTLIST ROW note CDATA #IMPLIED>
  <!ATTLIST ROW Package CDATA #IMPLIED>
  <!ATTLIST ROW Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="AdditionalNote" Caption="AdditionalNote" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Approved_by" Caption="Approved by" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="change_index" Caption="change index" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Cust__No" Caption="Cust. No" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Edited_by" Caption="Edited by" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Last_Rev__Date" Caption="Last Rev. Date" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Product_No_" Caption="Product No." Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Product_Number" Caption="Product Number" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="Release_No" Caption="Release No" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="descriptions" Caption="descriptions" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="mfg" Caption="mfg" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="note" Caption="note" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="Package" Caption="Package" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="Part_Number" Caption="Part Number" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="A. AMAR" ApprovedBy="A. AMAR" change_index="&#61;Projectchangeindex" Cust__No="TBD" Description="Printed Circuit Board" Designator="APCB" Edited_by="Thomas A. Shirley" Last_Rev__Date="03/20/2018" Product_No_="97101901" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="" note="" Package="" Part_Number="97101901" Value="97101901"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C1" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 100V X7R" Package="0805" Part_Number="" Value="2.2nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C2" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 100V X7R" Package="0805" Part_Number="" Value="2.2nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C7" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0805" Part_Number="" Value="220nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C8" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0805" Part_Number="" Value="220nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, EMIFIL, 3-TERMINAL" Designator="C9" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 50V 2A" Package="0805" Part_Number="" Value="22nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C10" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="470pF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C11" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="470pF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C12" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C13" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C14" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C15" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C16" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C17" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C18" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C19" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 100V COG" Package="1206" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C20" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0402" Part_Number="" Value="1nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C21" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0402" Part_Number="" Value="1nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C22" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0603" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C23" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0603" Part_Number="" Value="33nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C24" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0603" Part_Number="" Value="1uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C25" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0805" Part_Number="" Value="4.7uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C26" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="470pF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C27" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C28" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C29" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C30" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C31" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0402" Part_Number="" Value="1nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C33" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0402" Part_Number="" Value="10nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C35" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X7R" Package="0805" Part_Number="" Value="2.2uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C36" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X5R" Package="0603" Part_Number="" Value="4.7uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C37" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0603" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C38" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X5R" Package="0603" Part_Number="" Value="4.7uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C40" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0402" Part_Number="" Value="1nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C41" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 100V COG" Package="1206" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C42" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 100V COG" Package="1206" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C43" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C44" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="1206" Part_Number="" Value="10uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C45" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 50V X7R" Package="0603" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C46" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 16V X5R" Package="0805" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C47" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 16V X5R" Package="0805" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C48" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="&#61;ProjectAdditionalNote" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C49" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="47pF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C79" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C80" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C81" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="22pF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C82" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C83" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C84" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C85" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C86" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="20&#37; 25V X7R" Package="1210" Part_Number="" Value="22uF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C87" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="5&#37; 50V COG" Package="0402" Part_Number="" Value="47pF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C88" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C89" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C90" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X7R" Package="0402" Part_Number="" Value="22nF"></ROW>
    <ROW AdditionalNote="" Approved_by="" ApprovedBy="A. AMAR" change_index="" Cust__No="TBD" Description="CAPACITOR, CERAMIC" Designator="C91" Edited_by="Thomas A. Shirley" Last_Rev__Date="" Product_No_="" Product_Number="97101901" Quantity="1" Release_No="C006014" Title="MAZDA WIRELESS CHARGING MODULE" descriptions="&#61;Projectdescriptions" mfg="SEE NOTE 1" note="10&#37; 25V X5R" Package="0402" Part_Number="" Value="100nF"></ROW>